language: node_js
node_js:
  - "10"

cache: npm

jobs:
  include:
    - stage: Test
      env:
        - NODE_ENV=test
      script:
        - npm run lint
        - npm run test

    - stage: Release
      if: (branch = master OR branch = beta) AND type = push AND fork = false
      script: npm run semantic-release
